### ISSUE TITLE
missing return statement

### ISSUE THREAD

**Issue by crissdev** [seriema/npmalerts#7]
I might be wrong but shouldn't a return statement be after invoking the callback on error?

[db.js#L41](https://github.com/seriema/npmalerts/blob/master/lib/db.js#L41) and [db.js#L51](https://github.com/seriema/npmalerts/blob/master/lib/db.js#L51)

**Comment by seriema** [comment]
I wish Github would email me when someone writes on my repo's =)

I believe you're right! I'll fix that. Thanks!

Btw, do you use npmalerts? Do you find it useful?

**Comment by crissdev** [comment]
Email alerts can be enabled in `Settings > Notification center` :wink: 

I was more interested about the code of this project which I found out to be very well written. At some point I used https://www.versioneye.com/ but it turned out to be not so useful to me because I've just a few projects to maintain and `npm-check-updates` and `badges` are enough to me. But I think it's good to have `free` options for such things.

By the way, the `About` section in http://npmalerts.com/ is missing some spaces around the links.

**Comment by seriema** [comment]
That would send me emails on any repo I watch =/ I only want it for my own repos.

Thanks. Funny enough I met one of the founders for versioneye just yesterday! I didn't even know about the site before that. :D

I fixed the missing `return`s. Thanks for spotting it! There's a test failing for `npm` so I can't deploy this just yet though. Seems my hack caught up to me [npm.js#L13](https://github.com/seriema/npmalerts/blob/master/lib/npm.js#L13) hehe

Hehe yeah someone found those missing spaces too, and even fixed it for me: https://github.com/seriema/npmalerts-web/pull/1
